/**
 * Chinese → English routing lexicon.
 *
 * This catalog's skill names and descriptions are mostly English while the
 * instructions arriving here are mostly Chinese, so pure lexical overlap finds
 * almost nothing (`评审` never meets `review`). The lexicon is the bridge: a
 * query n-gram listed here also casts its English evidence tokens, at a
 * discounted weight, so a Chinese instruction can hit an English name or
 * description without an LLM call.
 *
 * Keys are the n-grams `tokenize` actually produces (bigrams/trigrams/full runs
 * of a CJK run, or a whole short term), so a key must be a substring that
 * survives tokenization. Extra entries can be supplied per row via the
 * `lexicon` config field; they are merged over these defaults.
 *
 * @module dsh-plugin-skill-autoroute/lib/lexicon
 */

/** Discount applied to every bridged token. */
export const BRIDGE_WEIGHT = 0.85

/** @type {Readonly<Record<string, readonly string[]>>} */
export const LEXICON = Object.freeze({
  // --- audio / sound -------------------------------------------------------
  音频: ['audio', 'sound'],
  声音: ['sound', 'audio'],
  音效: ['sound', 'sfx'],
  音响: ['audio'],
  混音: ['mix', 'mixing'],
  母带: ['master', 'mastering'],
  空间: ['spatial'],
  三维: ['spatial', '3d'],
  交互音乐: ['interactive', 'music'],
  自适应音乐: ['adaptive', 'music'],
  音乐: ['music'],
  对白: ['dialogue'],
  语音: ['speech', 'voice'],
  录音: ['recording', 'record'],
  转录: ['transcribe', 'transcription', 'whisper'],
  转文字: ['transcribe', 'whisper'],
  转写: ['transcribe', 'transcription', 'whisper'],
  听写: ['transcription'],
  对话: ['dialogue', 'conversation'],
  频谱: ['spectrum'],
  采样: ['sample'],
  合成: ['synthesis', 'synthesize'],
  声学: ['acoustic', 'acoustics'],
  耳机: ['headphone', 'hrtf'],
  双耳: ['binaural', 'hrtf'],
  引擎: ['engine'],
  中间件: ['middleware'],
  汽车: ['automotive', 'car'],
  车型: ['automotive', 'car'],
  车辆: ['automotive', 'vehicle'],
  座舱: ['cockpit', 'cabin'],
  转向: ['turn', 'indicator'],
  提示音: ['chime', 'tone'],
  指示灯: ['indicator', 'light'],
  车灯: ['light', 'lamp'],
  声浪: ['engine', 'sound'],
  原理: ['principle'],
  衰减: ['attenuation'],
  传播: ['propagation'],
  定位: ['positioning'],
  验收: ['acceptance', 'verify'],
  参数: ['parameter'],
  总线: ['bus'],
  事件: ['event'],
  批量: ['batch'],
  流水线: ['pipeline'],
  自动化: ['automation', 'automatic'],
  生成: ['generate', 'generation'],
  制作: ['create', 'build'],
  设计: ['design'],
  评审: ['review'],
  试听: ['listen', 'review'],
  测评: ['review', 'assessment'],
  评测: ['review', 'assessment'],
  工程: ['project'],
  无损: ['non-destructive'],
  非破坏: ['non-destructive'],
  候选: ['candidate'],
  标记: ['marker', 'mark'],
  切分: ['split', 'segment'],
  帧: ['frame'],
  品牌: ['brand'],
  标识: ['logo', 'brand'],
  商标: ['logo'],

  // --- video / post --------------------------------------------------------
  视频: ['video'],
  录像: ['recording', 'video'],
  录屏: ['screen', 'recording'],
  长视频: ['video'],
  短片: ['video', 'short'],
  剪辑: ['edit', 'editing'],
  剪成: ['edit'],
  片段: ['clip', 'segment'],
  碎片: ['clip', 'fragment'],
  出入点: ['in', 'out', 'edit'],
  时间线: ['timeline'],
  时间轴: ['timeline'],
  字幕: ['caption', 'subtitle'],
  对轴: ['sync', 'caption'],
  镜头: ['shot', 'frame'],
  关键帧: ['keyframe', 'frame'],
  抽帧: ['frame', 'extract'],
  抽取: ['extract'],
  成片: ['delivery', 'final'],
  交付: ['delivery'],
  旁白: ['narration', 'narrated'],
  讲成: ['narrated'],
  讲解: ['narrated', 'explain'],
  科普: ['science'],
  直播: ['live', 'stream'],
  转码: ['transcode'],

  // --- documents / publishing ---------------------------------------------
  文档: ['document', 'docx'],
  出版: ['publish', 'publication'],
  发布: ['publish'],
  发表: ['publish', 'submission'],
  投稿: ['submission', 'publish'],
  笔记: ['notes', 'note'],
  导入: ['import'],
  语雀: ['yuque', 'lakebook'],
  飞书: ['feishu', 'lark'],
  文档站: ['wiki', 'documentation'],
  知识库: ['knowledge'],
  知识: ['knowledge'],
  可溯源: ['traceable'],
  溯源: ['traceable', 'source'],
  元数据: ['metadata'],
  图表: ['figure', 'chart'],
  数据: ['data'],
  期刊: ['journal'],
  论文: ['paper', 'article', 'literature'],
  文献: ['literature', 'paper'],
  课件: ['lecture', 'slide', 'deck'],
  演示: ['presentation', 'slide'],
  幻灯片: ['slide', 'deck'],
  母版: ['template', 'master'],
  占位符: ['placeholder'],
  备注: ['notes'],
  表单: ['form'],
  表格: ['spreadsheet', 'xlsx'],
  工作簿: ['workbook', 'xlsx'],
  合并: ['merge'],
  拆分: ['split'],
  解析: ['parse'],
  排版: ['layout', 'typeset'],
  导出: ['export'],
  教案: ['lesson', 'teaching'],
  课程: ['course', 'lecture'],
  讲稿: ['lecture', 'script'],

  // --- research / knowledge work ------------------------------------------
  调研: ['research'],
  研究: ['research'],
  综述: ['review', 'literature'],
  情报: ['intel', 'intelligence'],
  选题: ['topic'],
  深度: ['deep', 'in-depth'],
  月度: ['monthly'],
  每月: ['monthly'],
  本月: ['monthly'],
  当月: ['monthly'],
  这个月: ['monthly'],
  汇总: ['summary', 'roundup', 'digest'],
  复盘: ['review', 'retrospective'],
  归档: ['archive'],
  治理: ['governance'],
  迭代: ['iteration', 'iterate'],
  整理: ['curate', 'organize'],
  提炼: ['distill', 'curate'],
  蒸馏: ['distill'],
  一本书: ['book'],
  这本书: ['book'],
  图书: ['book'],

  // --- skills / plugins / harness -----------------------------------------
  技能: ['skill'],
  插件: ['plugin'],
  组合: ['composition', 'cordis'],
  持久化: ['durable', 'persistent'],
  重启: ['restart'],
  上游: ['upstream'],
  修复: ['fix'],
  迁移: ['migrate', 'migration'],
  授权: ['authority'],
  取证: ['forensics'],
  打包: ['bundle'],
  仓库: ['repo', 'repository'],
  检出: ['checkout'],
  维护: ['maintain', 'maintenance'],
  审计: ['audit'],
  清单: ['inventory'],
  哪些: ['inventory', 'list', 'which'],
  盘点: ['inventory', 'audit'],
  装了: ['install'],
  复用: ['reuse'],
  新建: ['create'],
  智能体: ['agent'],
  代理: ['agent'],
  子代理: ['subagent'],
  规则: ['rule', 'spec'],
  规范: ['spec', 'standard'],
  接口: ['api'],
  配置: ['config'],
  安装: ['install'],
  查找: ['find', 'search'],
  寻找: ['find', 'search'],
  搜索: ['search'],
  选择: ['select', 'choose'],
  优化: ['optimize', 'improve'],
  评分: ['score', 'grade'],
  改进: ['improve', 'self-improving'],
  天气: ['weather'],
  浏览器: ['browser'],
  定时: ['schedule', 'scheduled'],
  提醒: ['reminder', 'schedule'],
  恢复: ['resume'],
  任务: ['task'],
  计划: ['plan', 'planning'],
  规划: ['planning'],

  // --- language ------------------------------------------------------------
  翻译: ['translate', 'translation', 'fanyi'],
  昆仑: ['kunlun'],
  术语: ['terminology', 'glossary'],
  中文: ['chinese'],
  英文: ['english'],
  一致性: ['consistency', 'consistent'],

  // --- workspace proper nouns (skill names are pinyin or latin) ------------
  游戏: ['game'],
  李白: ['libai'],
  天工: ['tiangong'],
  鲁班: ['luban'],
})
